require_relative './pieces/piece.rb'
require_relative './pieces/rook.rb'
require_relative './pieces/bishop.rb'
require_relative './pieces/queen.rb'
require_relative './pieces/slideable.rb'
require_relative './pieces/null.rb'
# require_relative './pieces/piece.rb'